apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: todolist-keyvault
  labels: 
    io.kompose.service: todo-list-web
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: d56ddb0c-19a7-4df4-bae1-9c39d6372015
    keyvaultName: kvayu78
    objects:  |
      array:
        - |
          objectName: config
          objectType: secret
          objectAlias: config.json
    tenantId: cf36141c-ddd7-45a7-b073-111f66d0b30c